language: node_js
node_js: 8
script: gulp
deploy:
  provider: releases
  api_key:
    secure: uIibGjDiOH1ezYXx0wSTRUzhm+sOVqnJgpKaZDwm2mwLyQYm8v3BX7kse2p2cN4x03ZDKhrRhihKGMkZBtJt1+j5bQ02aUqTWxbfgCcq4fqe52mZ23ZnyvBQgkJex42wX5I0OVoJcgy344yd3Z8lcNn8aRYwIbLyIW3I2UmyPeWgWRpAGKUl+Fh0UIsjpaluXGei8UVGPQQMK04ID7nWVPKsOyLWnsEEgpgtTFbmFPjIlOTJSoabMVuSwyvIyXV7r10zaXXfKZvM2xdHKl59T1fIwIKtrHL7OFEyabDBBQ2zCz9PRk5O1V/LyUGgdB8tWb23YZtk35R+NjIbQl7rFbfOiB0TdTgjPNGFwc3mjQ5pGWrQl7lgezYXjruPgti2aLvpdoViWu53y2TAcKKHZbeSlrqG7rYzod/JjuG29UJpqFSr5B4of5LZaEtAsR91TgJM4dOX12cPNs9T97XA+6qUjCX8MzbslfN9ifosX0ZhnER2n3r1cVOeZ2vov7VvyOISbkrjM5q9Ma3SYv6v0yqDdkLA2D1T/yFgOcOuZ1wUfncfILe5nuPJY0maOMjp+rm1ZvIrQk+PsjiLxkxoi0R+nNOV1oQ9hDDeowDKdDOnPb4npK2v3oMmHpwtlwP31hL1R/eJuYX4hsQTUWnUhfJmTQQF5pA7PhuTUQnmMOY=
  file:
    - dist/bifrost.js
    - dist/bifrost.min.js
  skip_cleanup: true
  on:
    tags: true
